
package br.gov.coaf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComunicacaoService", targetNamespace = "http://www.gov.br/coaf/", wsdlLocation = "file:/home/oem/Development/workspace/coaf-soap-client/src/main/resources/wsdl/COAF.ComunicacaoService.wsdl")
public class ComunicacaoService_Service
    extends Service
{

    private final static URL COMUNICACAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMUNICACAOSERVICE_EXCEPTION;
    private final static QName COMUNICACAOSERVICE_QNAME = new QName("http://www.gov.br/coaf/", "ComunicacaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/oem/Development/workspace/coaf-soap-client/src/main/resources/wsdl/COAF.ComunicacaoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMUNICACAOSERVICE_WSDL_LOCATION = url;
        COMUNICACAOSERVICE_EXCEPTION = e;
    }

    public ComunicacaoService_Service() {
        super(__getWsdlLocation(), COMUNICACAOSERVICE_QNAME);
    }

    public ComunicacaoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMUNICACAOSERVICE_QNAME, features);
    }

    public ComunicacaoService_Service(URL wsdlLocation) {
        super(wsdlLocation, COMUNICACAOSERVICE_QNAME);
    }

    public ComunicacaoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMUNICACAOSERVICE_QNAME, features);
    }

    public ComunicacaoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComunicacaoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComunicacaoService
     */
    @WebEndpoint(name = "ComunicacaoServicePort")
    public ComunicacaoService getComunicacaoServicePort() {
        return super.getPort(new QName("http://www.gov.br/coaf/", "ComunicacaoServicePort"), ComunicacaoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComunicacaoService
     */
    @WebEndpoint(name = "ComunicacaoServicePort")
    public ComunicacaoService getComunicacaoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.gov.br/coaf/", "ComunicacaoServicePort"), ComunicacaoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMUNICACAOSERVICE_EXCEPTION!= null) {
            throw COMUNICACAOSERVICE_EXCEPTION;
        }
        return COMUNICACAOSERVICE_WSDL_LOCATION;
    }

}
