
package br.gov.coaf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComunicacaoService", targetNamespace = "http://www.gov.br/coaf/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComunicacaoService {


    /**
     * 
     * @param lote
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarLoteComunicacao")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "CancelarLoteComunicacao", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.CancelarLoteComunicacao")
    @ResponseWrapper(localName = "CancelarLoteComunicacaoResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.CancelarLoteComunicacaoResponse")
    public String cancelarLoteComunicacao(
        @WebParam(name = "lote", targetNamespace = "http://www.gov.br/coaf/")
        String lote);

    /**
     * 
     * @param lote
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviarLoteComunicacao")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "EnviarLoteComunicacao", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.EnviarLoteComunicacao")
    @ResponseWrapper(localName = "EnviarLoteComunicacaoResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.EnviarLoteComunicacaoResponse")
    public String enviarLoteComunicacao(
        @WebParam(name = "lote", targetNamespace = "http://www.gov.br/coaf/")
        String lote);

    /**
     * 
     * @param lote
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetificarLoteComunicacao")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "RetificarLoteComunicacao", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.RetificarLoteComunicacao")
    @ResponseWrapper(localName = "RetificarLoteComunicacaoResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.RetificarLoteComunicacaoResponse")
    public String retificarLoteComunicacao(
        @WebParam(name = "lote", targetNamespace = "http://www.gov.br/coaf/")
        String lote);

    /**
     * 
     * @param lote
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReciboLoteComunicacao")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "ReciboLoteComunicacao", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.ReciboLoteComunicacao")
    @ResponseWrapper(localName = "ReciboLoteComunicacaoResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.ReciboLoteComunicacaoResponse")
    public String reciboLoteComunicacao(
        @WebParam(name = "lote", targetNamespace = "http://www.gov.br/coaf/")
        String lote);

    /**
     * 
     * @param protocolo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SolicitaProtocoloComunicacao")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "SolicitaProtocoloComunicacao", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.SolicitaProtocoloComunicacao")
    @ResponseWrapper(localName = "SolicitaProtocoloComunicacaoResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.SolicitaProtocoloComunicacaoResponse")
    public String solicitaProtocoloComunicacao(
        @WebParam(name = "protocolo", targetNamespace = "http://www.gov.br/coaf/")
        String protocolo);

    /**
     * 
     * @param lote
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SolicitaReciboEnvio")
    @WebResult(targetNamespace = "http://www.gov.br/coaf/")
    @RequestWrapper(localName = "SolicitaReciboEnvio", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.SolicitaReciboEnvio")
    @ResponseWrapper(localName = "SolicitaReciboEnvioResponse", targetNamespace = "http://www.gov.br/coaf/", className = "br.gov.coaf.SolicitaReciboEnvioResponse")
    public String solicitaReciboEnvio(
        @WebParam(name = "lote", targetNamespace = "http://www.gov.br/coaf/")
        String lote);

}
